### ISSUE TITLE
Action doesn't seem to be traversing all sitemap files

### ISSUE THREAD

**Issue by bmarotta** [bojieyang/indexnow-action#280]
Hi,

It seems that if a sitemap references other sitemaps, it seems that only the main sitemap is being parsed.

Check example here:

https://fluzaonews.com.br/sitemap-index.xml

This sitemap is generated automatically by [Astro](https://docs.astro.build/en/guides/integrations-guide/sitemap/),

This is the result of the workflow action:

```
Run bojieyang/indexnow-action@v2
  with:
    sitemap-location: https://fluzaonews.com.br/sitemap-index.xml
    key: ***
    since: 1
    since-unit: day
    endpoint: www.bing.com
    limit: 100
    timeout: 10000
    failure-strategy: ignore
No candidate urls need to submit.
```

**Comment by bojieyang** [comment]
This is because your sitemap does not have a lastmod tag in each url entry, so it is excluded by default.
As a workaround, you can add the lastmod tag to each url entry and it will work as expected.

And I will add an optional flag to force ignore the lastmod check when the tag is not present. This will be released in the next few days. If you are unable to add the lastmod tag in your sitemap, please wait for this release.

**Comment by bojieyang** [comment]
@bmarotta the new version is released.
set `lastmod-required` option to false should work as expected. 
like below:
```
steps:
      - name: indexnow-action
        uses: bojieyang/indexnow-action@v2
        with:
          sitemap-location: "{YOUR SITEMAP URL}"
          since: 1
          since-unit: "day"
          key: "{YOUR KEY}"
          lastmod-required: false
```
